### PR TITLE
BLOCKER json-pointer vulnerability replaced with jsonpointer

### PR DESCRIPTION
**Pull request by neil-stephen-mcgonigle**
…ced with jsonpointer

### CODE REVIEW

**Comment by neil-stephen-mcgonigle** [comment]
image

**Review by sinclairs — CHANGES_REQUESTED** [review]
Looks good. All the tests passing?

Can you update the commit message before merging please e.g.

"Replace json-pointer module with jsonpointer"

**Comment by sinclairs** [comment]
Also I'd ignore the release a the moment. Not sure why it's at 1.0.0 as it isn't in production. Def needs some refactoring before release.

**Comment by neil-stephen-mcgonigle** [comment]
> Looks good. All the tests passing?
> 
> Can you update the commit message before merging please e.g.
> 
> "Replace json-pointer module with jsonpointer"

all tests are passing and I will change the commit message.

**Review by sinclairs — APPROVED** [review]

**Pull request merged**
